In [1]:
import numpy as np

In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp

8.0

In [7]:
test_cov = a_centered_sp / (a.shape[0] - 1)
test_cov

2.0

In [8]:
cov = np.cov(a.T)[0, 1]
cov

2.0